<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_content-blocks',
		'title' => 'Content Blocks',
		'fields' => array (
			array (
				'key' => 'field_53d84cc33c528',
				'label' => 'Content Blocks',
				'name' => 'content_blocks',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Latest News',
						'name' => 'latest_news',
						'display' => 'row',
						'min' => 0,
						'max' => 1,
						'sub_fields' => array (
							array (
								'key' => 'field_53dee6de2ef83',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53dee7172ef84',
								'label' => 'News Category',
								'name' => 'news_category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'More News',
						'name' => 'more_news',
						'display' => 'row',
						'min' => '0',
						'max' => '1',
						'sub_fields' => array (
							array (
								'key' => 'field_53e181d9dbaac',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e1923ef2886',
								'label' => 'More News Category',
								'name' => 'more_news_category',
								'type' => 'taxonomy',
								'instructions' => 'Choose one or more news categories. Select none to show all news. Posts already seen in Slider or Latest news will not be repeated here.',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'checkbox',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_53e802eaf9170',
								'label' => 'Items',
								'name' => 'items',
								'type' => 'select',
								'instructions' => 'How man news items to show.',
								'column_width' => '',
								'choices' => array (
									1 => 1,
									2 => 2,
									3 => 3,
									4 => 4,
									5 => 5,
									6 => 6,
									7 => 7,
									8 => 8,
									9 => 9,
									10 => 10,
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'Medium News',
						'name' => 'medium_news',
						'display' => 'row',
						'min' => '0',
						'max' => '1',
						'sub_fields' => array (
						array (
							'key' => 'field_z53dee6de2ef83',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
						),
						array (
							'key' => 'field_z53dee7172ef84',
							'label' => 'News Category',
							'name' => 'news_category',
							'type' => 'taxonomy',
							'column_width' => '',
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 0,
							'load_save_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
							array (
								'key' => 'field_z53e802eaf9170',
								'label' => 'Items',
								'name' => 'items',
								'type' => 'select',
								'instructions' => 'How many news items to show.',
								'column_width' => '',
								'choices' => array (
									2 => 2,
									4 => 4,
									6 => 6,
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 3,
							),
						),
					),
					array (
						'label' => 'Basic Slider',
						'name' => 'basic_slider',
						'display' => 'row',
						'min' => '0',
						'max' => '1',
						'sub_fields' => array (
						array (
							'key' => 'field_bz53dee6de2ef83',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
						),
						array (
							'key' => 'field_bz53dee7172ef84',
							'label' => 'News Category',
							'name' => 'news_category',
							'type' => 'taxonomy',
							'column_width' => '',
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 0,
							'load_save_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						),
					),
					array (
						'label' => 'Youtube',
						'name' => 'youtube',
						'display' => 'table',
						'min' => 0,
						'max' => 1,
						'sub_fields' => array (
							array (
								'key' => 'field_53d86d317f98d',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d84d4e3c529',
								'label' => 'Youtube ID',
								'name' => 'youtube_id',
								'type' => 'text',
								'instructions' => 'The YouTube username or channel or Playlist ID eg: https://www.youtube.com/user/<span class="aggro-example">username</span> or https://www.youtube.com/channel/<span class="aggro-example">channel</span> or the YouTube playlist ID eg: https://www.youtube.com/playlist?list=<span class="aggro-example">playlistid</span>',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d85f20e3577',
								'label' => 'Video Thumbs',
								'name' => 'video_thumbs',
								'type' => 'radio',
								'instructions' => 'The number of thumbnails to display',
								'column_width' => '',
								'choices' => array (
									3 => 3,
									6 => 6,
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 3,
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_53daf50f2c3f8',
								'label' => 'Channel or Playlist',
								'name' => 'channel_or_playlist',
								'type' => 'radio',
								'instructions' => 'Is this a YouTube Channel or Playlist',
								'required' => 1,
								'column_width' => '',
								'choices' => array (
									'channel' => 'Channel',
									'playlist' => 'Playlist',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Custom Section',
						'name' => 'custom_section',
						'display' => 'row',
						'min' => 0,
						'max' => 5,
						'sub_fields' => array (
							array (
								'key' => 'field_53d86a1961d26',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d86a8f61d27',
								'label' => 'Section Text',
								'name' => 'section_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'basic',
								'media_upload' => 'no',
							),
							array (
								'key' => 'field_53d86ac661d28',
								'label' => 'Section Image',
								'name' => 'section_image',
								'type' => 'image',
								'instructions' => 'Optional',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Gallery',
						'name' => 'gallery',
						'display' => 'row',
						'min' => 0,
						'max' => 1,
						'sub_fields' => array (
							array (
								'key' => 'field_53d987bde6364',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d8961d7f8d0',
								'label' => 'Gallery Images',
								'name' => 'gallery_images',
								'type' => 'gallery',
								'column_width' => '',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Feature Section',
						'name' => 'feature_section',
						'display' => 'row',
						'min' => 0,
						'max' => 1,
						'sub_fields' => array (
							array (
								'key' => 'field_otawp6gx3qap7',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),

						),
					),
				),
				'button_label' => 'Add Content Block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'landing',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '20',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 20,
	));
}
?>