<?php 
if( function_exists('register_field_group') ):

register_field_group(array (
	'title' => 'Feature Competition',
	'id' => 'acf_feature-Competition',
	'fields' => array (
		array (
			'key' => 'field_5732b9770d98b',
			'label' => 'Landing Page Fixtures and Results',
			'name' => 'landing_page_fixtures_and_results',
			'type' => 'repeater',
			'instructions' => '',
			'min' => '',
			'max' => 1,
			'layout' => 'table',
			'button_label' => 'Add Competition',
			'sub_fields' => array (
				array (
					'key' => 'field_5732b9770ed21',
					'label' => 'competition Name',
					'name' => 'landing_page_competition_name',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5732b9770ed35',
					'label' => 'Competition ID',
					'name' => 'landing_page_competition_id',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5732b9770ed5b',
					'label' => 'Logo',
					'name' => 'landing_page_logo',
					'type' => 'image',
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_5732b9770d99f',
			'label' => 'Fixtures logo',
			'name' => 'landing_page_fixtures_logo',
			'type' => 'repeater',
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_5732b977141ec',
					'label' => 'Fixtures Team logo',
					'name' => 'landing_page_fixtures_team_logo',
					'type' => 'image',
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5732b977141ff',
					'label' => 'team id',
					'name' => 'landing_page_team_id',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5732b9771420f',
					'label' => 'Team Name',
					'name' => 'landing_page_team_name',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
                array (
								'key' => 'field_w9vuphpnt0z8x',
								'label' => 'Feature background Image',
								'name' => 'feature_image',
								'type' => 'image',
								'column_width' => '',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'landing',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif; ?>