<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_match-centre',
		'title' => 'Match Centre',
		'fields' => array (
			array (
				'key' => 'field_53e033a18a9ea',
				'label' => 'Match Centre Type',
				'name' => 'match_centre_type',
				'type' => 'radio',
				'instructions' => 'Choose the Match Centre Type',
				'choices' => array (
					0 => 'None',
					1 => 'Match Centre',
					2 => 'Live Stats',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 0,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_aaa53e033a18a9ea',
				'label' => 'Show Match Centre On All Associated Items',
				'name' => 'match_centre_everywhere',
				'type' => 'radio',
				'instructions' => 'Show?',
				'choices' => array (
					0 => 'No',
					1 => 'Yes'
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 0,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53e0350a5a2fd',
				'label' => 'Competitions - Live Stats',
				'name' => 'competitions_ls',
				'type' => 'repeater',
				'instructions' => 'Enter comp id\'s and labels.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e033a18a9ea',
							'operator' => '==',
							'value' => '2',
						),
					),
					'allorany' => 'any',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_53e0355b5a2fe',
						'label' => 'Competition ID',
						'name' => 'comp_id',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e033a18a9ea',
									'operator' => '==',
									'value' => '2',
								),
								array (
									'field' => 'field_53e033a18a9ea',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => 20,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e035e15a300',
						'label' => 'Competition label',
						'name' => 'comp_label',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53e033a18a9ea',
									'operator' => '==',
									'value' => '1',
								),
								array (
									'field' => 'field_53e033a18a9ea',
									'operator' => '==',
									'value' => '2',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e0439ad9d9a',
						'label' => 'Competition Link',
						'name' => 'comp_link',
						'type' => 'text',
						'instructions' => 'Full URL to Competition including http://',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53ec146253ab8',
						'label' => 'User ID',
						'name' => 'user_id',
						'type' => 'text',
						'instructions' => 'Live Stats User ID',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Competition',
			),
			array (
				'key' => 'field_53e067998049b',
				'label' => 'User ID',
				'name' => 'ls_user_id',
				'type' => 'number',
				'instructions' => 'Live Stats User ID',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e033a18a9ea',
							'operator' => '==',
							'value' => '2',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53e461c03397d',
				'label' => 'Match Centre',
				'name' => 'match_centre',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e033a18a9ea',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_53e461fe3397e',
						'label' => 'Competition Name',
						'name' => 'comp_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e4621c3397f',
						'label' => 'Competition ID',
						'name' => 'comp_id',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e4624933980',
						'label' => 'Round Number',
						'name' => 'round_number',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							0 => 0,
							1 => 1,
							2 => 2,
							3 => 3,
							4 => 4,
							5 => 5,
							6 => 6,
							7 => 7,
							8 => 8,
							9 => 9,
							10 => 10,
							11 => 11,
							12 => 12,
							13 => 13,
							14 => 14,
							15 => 15,
							16 => 16,
							17 => 17,
							18 => 18,
							19 => 19,
							20 => 20,
							21 => 21,
						),
						'default_value' => 0,
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53e462b633981',
						'label' => 'Time of Season',
						'name' => 'time_of_season',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							-1 => 'Regular Season',
							1001 => 'Finals',
							1 => 'Pool 1',
							2 => 'Pool 2',
						),
						'default_value' => '-1',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Competition',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'landing',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 3,
	));
}
?>